name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.3'

    steps:
    - uses: actions/checkout@v3
    - uses: oxidize-rb/actions/setup-ruby-and-rust@54cd25fbb69a70a5e80a016e6f6dce4c5f3bf7be
      with:
        rustup-toolchain: stable
        ruby-version: ${{ matrix.ruby }}
        cache-version: v1
        bundler-cache: true
        cargo-cache: true
        cargo-cache-extra-path: |
          ext/perb/target
    - name: Run the default task
      run: bundle exec rake
